const ImagesPath = {
    splash: {
        bgImg: require('./images/splash/Updated_Splash.png'),
    },
    language: {
        logo: require('./images/language/logo.png'),
        checkIcon: require('./images/language/check_icon.png'),
        india: require('./images/language/india.png'),
        uk: require('./images/language/uk.png'),
    },
    signUp: {
        callIcon: require('./images/signUp/call_icon.png'),
        backIcon: require('./images/signUp/back.png'),
        logoIcon: require('./images/signUp/logo.png'),
        EmailIcon: require('./images/signUp/email_icon.png'),
        tbIcon: require('./images/signUp/tb_icon.png'),
        show: require('./images/signUp/show.png'),
        hide: require('./images/signUp/hide.png'),
        crossTerms : require('./images/signUp/crossTerms.png'),

    },
    onafterprint: {
        MenIcon: require('./images/onboarding/men.png'),
        womenIcon: require('./images/onboarding/Women.png'),
        intro:require('./images/onboarding/intro.png'), 
        otherIcon: require('./images/onboarding/Others_primary.png'),
        dow_arrIcon: require('./images/onboarding/dow_arr.png'),
        general_icon: require('./images/onboarding/general_icon.png'),
        child_icon: require('./images/onboarding/child_icon.png'),
        redio_check: require('./images/onboarding/redio_check.png'),
        redio_uncheck: require('./images/onboarding/redio_uncheck.png'),
        check_icon: require('./images/onboarding/check_icon.png'),
        uncheck_icon: require('./images/onboarding/uncheck_icon.png'),
        add_icon: require('./images/onboarding/add_icon.png'),
        plush_icon: require('./images/onboarding/plush_icon.png'),
        cancel_icon: require('./images/onboarding/cancel_icon.png'),
        edit_icon: require('./images/onboarding/edit_icon.png'),
        time_icon: require('./images/onboarding/time_icon.png'),
        calender_icon: require('./images/onboarding/updated_calendar.png'),
        delete_icon: require('./images/onboarding/delete_icon.png'),
        camera_icon: require('./images/onboarding/camera_icon.png'),
        cancel_primary: require('./images/onboarding/cancel_primary.png'),
        radio_check: require('./images/onboarding/radio_check.png'),
        check_box: require('./images/onboarding/check_box.png'),
        cancel2_primary: require('./images/onboarding/cancel2_primary.png'),
        add_primary: require('./images/onboarding/add_primary.png'),
        add_primary_white: require('./images/onboarding/add_primary_new.png'),
        check_primary: require('./images/onboarding/check_primary.png'),
        radio_primary: require('./images/onboarding/radio_primary.png'),
        arrow: require('./images/onboarding/arrow.png'),
        uncheck_primary: require('./images/onboarding/uncheck_primary.png'),
        cross_primary: require('./images/onboarding/cross_primary.png'),
        upload: require('./images/onboarding/upload.png'),
        check_popup: require('./images/onboarding/check_popup.png'),
        logout_primary: require('./images/onboarding/logout_primary.png'),
        pencil_primary: require('./images/onboarding/pencil_primary.png'),
        cross: require('./images/onboarding/cross.png'),
    },
    home: {
        home_icon: require('./images/home/home.png'),
        home_logo: require('./images/home/home_logo.png'),
        calender_icon: require('./images/home/calender.png'),
        man_icon: require('./images/home/man.png'),
        wallet_icon: require('./images/home/wallet.png'),
        dollar_icon: require('./images/home/dollar.png'),
        menu_icon: require('./images/home/menu_icon.png'),
        bell_icon: require('./images/home/bell_icon.png'),
        time_icon: require('./images/home/appointment_time.png'),
        manImg: require('./images/home/new_patient.png'),
        add_patient_icon: require('./images/home/add-patient-icon.png'),
        add_prescriptions: require('./images/home/add_prescriptions.png'),
        capsule_icon: require('./images/home/capsule_icon.png'),
        bottle_icon: require('./images/home/bottle_icon.png'),
        right_arrow: require('./images/home/right_arrow.png'),
        down_arrow: require('./images/home/down_arrow.png'),
        delete: require('./images/home/bin_dark.png'),
        add_appointments: require('./images/home/add_appointments.png'),
        no_appointments: require('./images/home/no-appointments.png'),
        three_dots: require('./images/home/menu.png'),
        videoCall: require('./images/home/videoCall.png'),
        ipsum_icon: require('./images/home/ipsum.png'),
        linearGradient_img: require('./images/home/linearGradient_img.png'),
        cloge_icon: require('./images/home/cloge_icon.png'),
        add_plus: require('./images/home/add_plus.png'),
        add_artic: require('./images/home/add_artic.png'),
        doctor_pic: require('./images/home/doctor_girl.jpeg'),
        micPres: require('./images/home/micPres.jpeg'),
        eclipse: require('./images/home/Eclipse.jpeg'),
        soundwaves: require('./images/home/soundwaves.png'),
        micred: require('./images/home/micred.png'),
        logo_primary: require('./images/onboarding/logo1.png'),
        download: require('./images/home/download_new.png'),
        Search_primary: require('./images/home/Search_primary.png'),
        calender: require('./images/home/calender_home.png'),
        patient_info: require('./images/home/medical-records.png'),
        user_profile: require('./images/home/user_profile.png'),
        background: require('./images/home/background.png'),
        settings_home: require('./images/home/settings_home.png'),
        bell_white: require('./images/home/bell_white.png'),
        search_medicine: require('./images/home/search-medicine.png'),
        articles: require('./images/home/articles.png'),
        patient_review: require('./images/home/positive-review.png'),
        xPatient: require('./images/home/xPatient.png'),
        cross_icon: require('./images/home/cross_icon.png'),
        search: require('./images/home/search.png'),
        delete_icon: require('./images/home/delete_icon.png'),
        terms_and_condition: require('./images/home/terms-and-conditions.png'),
        review_icon: require('./images/home/review_icon.png'),
        arrow_covered: require('./images/home/arrow_covered.png'),
        power_icon: require('./images/home/power_icon.png'),
        profile_icon: require('./images/home/Profile.png'),
        white_arrow: require('./images/home/white_arrow.png'),
        filter_icon: require('./images/home/filter_icon.png'),
        menu_invoice: require('./images/home/menu_invoice.png'),
        download_invoice: require('./images/home/download_invoice.png'),
        share_invoice: require('./images/home/share_invoice.png'),
        consentForm : require('./images/home/consentForm.png'),
        star : require('./images/home/star.png'),
        drug : require('./images/home/drug.jpg')
    },
    earning:{
        sortBy_icon: require('./images/earning/SortBy_icon.png'),
        video_earning: require('./images/earning/video_earning.png'),
        audio_earning: require('./images/earning/audio_earning.png'),
        chat_earning: require('./images/earning/chat_earning.png'),
        home_earning: require('./images/earning/home_earning.png'),
        clinic_earning: require('./images/earning/clinic_earning.png'),
        downlo_icon: require('./images/earning/downlo_icon.png'),
    },
    sideMenu:{
        invoices_icon: require('./images/sideMenu/Invoices_primary.png'),
        articles_icon: require('./images/sideMenu/article_primary.png'),
        rate_us_icon: require('./images/sideMenu/rateus_primary.png'),
        delete_account: require('./images/sideMenu/delete_primary.png'),
        logout_icon: require('./images/sideMenu/logout_icon.png'),
        Invoices: require('./images/sideMenu/Invoices_primary.png'),
        Articles: require('./images/sideMenu/article_primary.png'),
        RateUs: require('./images/sideMenu/rateus_primary.png'), 
        //NotificationOnOff: require('./images/sideMenu/Notification.png'), 
        //DeleteAccount: require('./images/sideMenu/DeleteAccount.png'),  
        // Logout: require('./images/sideMenu/Logout.png'), 
        Add: require('./images/sideMenu/Add.png'), 
        Bell: require('./images/sideMenu/bell_frame_primary.png'), 
        Line: require('./images/sideMenu/Line.png'),
        Calender: require('./images/sideMenu/Calender.png')
    },
    profile:{
        setting_icon:  require('./images/profile/setting_icon.png'),
        category_icon:  require('./images/profile/category_icon.png'),
        sub_category_icon:  require('./images/profile/sub_category_icon.png'),
        type_icon:  require('./images/profile/type_icon.png'),
        add_availability_icon:  require('./images/profile/add_availability_icon.png'),
        edit_icon:  require('./images/profile/edit_icon.png'),
        prof_setting: require('./images/profile/prof_setting.png'),
        selec_avail: require('./images/profile/selec_avail.png'),
        selec_cate: require('./images/profile/selec_cate.png'),
        selec_health: require('./images/profile/selec_health.png'),
        selec_type: require('./images/profile/selec_type.png'),
        doc_man: require('./images/profile/doc_man.png'),

    },
    video: {
        volume_icon: require('./images/video/volume.png'),
        un_volume_icon:  require('./images/video/un_volume.png'),
        camera_change: require('./images/video/camera_change.png'),
        mute_icon: require('./images/video/mute.png'),
        un_mute_icon: require('./images/video/un_mute.png'),
        video_camera_icon: require('./images/video/video_camera.png'),
        minimise_icon: require('./images/video/minimise_icon.png'),
        more_icon_icon: require('./images/video/more_icon.png'),
        stop_video_icon: require('./images/video/stop_video.png'),

    },
    LegalBridge:{
        bell: require('./images/LegalBridge/bell.png'),
        settings: require('./images/LegalBridge/settings.png'),
        search: require('./images/LegalBridge/search.png'),
        court1: require('./images/LegalBridge/court1.png'),
        court2: require('./images/LegalBridge/court2.png'),
        intro: require('./images/LegalBridge/lawyer.png'),
        intro2: require('./images/LegalBridge/lawyer2.png'),
        captcha: require('./images/LegalBridge/captcha.png'),
        legalcase: require('./images/LegalBridge/legalcase.png'),
        notary: require('./images/LegalBridge/notary.png'),
        certificates: require('./images/LegalBridge/certificates.png'),
        chat: require('./images/LegalBridge/chat.png'),
        agreement: require('./images/LegalBridge/agreement.png'),


    }
}

export default ImagesPath;